import anime from 'animejs';
import lightGallery from 'lightgallery';
import 'lightgallery/css/lightgallery-bundle.min.css'
// Plugins
import lgThumbnail from 'lightgallery/plugins/thumbnail'
import fullscreen from 'lightgallery/plugins/fullscreen'
import lgZoom from 'lightgallery/plugins/zoom'
//SWIPER
// import Swiper bundle with all modules installed
import Swiper from 'swiper/bundle';

// import styles bundle
import 'swiper/css/bundle';

function afterLoad(){const e=document.getElementById("cookie-banner"),o=document.getElementById("accept-cookies");"accepted"==localStorage.getItem("cookieConsent")&&(e.style.display="none"),o.addEventListener("click",()=>{localStorage.setItem("cookieConsent","accepted"),e.style.display="none"}),null!=document.getElementById("notification")&&setTimeout(()=>{document.getElementById("notification").style.visibility="hidden"},8e3),lightGallery(document.getElementById("open-google-map"),{selector:"this",download:!1,closeOnTap:!0,closable:!0,mobileSettings:{showCloseIcon:!0},hideScrollbar:!0});new Swiper(".swiper",{loop:!0,speed:800,autoplay:{delay:5e3,disableOnInteraction:!1}}),new Swiper(".mySwiper",{grabCursor:!0,loop:!0,autoplay:{delay:5e3,disableOnInteraction:!1},speed:3e3,effect:"cube",cubeEffect:{shadow:!0,slideShadows:!0,shadowOffset:20,shadowScale:.94},init:!0}),new Swiper(".carrousel_instagram")}function scrollToSection(e){var o;e.includes("#")&&(o=document.querySelector(e),document.getElementById("drawer-navigation").classList.add("-translate-x-full"),window.scrollTo({behavior:"smooth",top:"#totop"==e?0:o.offsetTop-50}))}document.addEventListener("DOMContentLoaded",()=>{document.querySelector("body").classList.add("overflow-y-auto"),document.querySelector(".preloader").style.display="none",afterLoad()}),window.gallery=function(e){const o=document.querySelectorAll("img.lazy"),t=document.querySelectorAll("video.lazy"),n=new IntersectionObserver((e,t)=>{e.forEach(e=>{if(e.isIntersecting){const o=e.target;o.src=o.dataset.src,o.classList.add("loaded"),t.unobserve(o)}})});o.forEach(e=>{n.observe(e)}),t.forEach(e=>{n.observe(e)}),e.forEach(e=>{"CAROUSEL_ALBUM"!=e.media_type&&"IMAGE"!=e.media_type||null!=(e=document.getElementById(e.id))&&lightGallery(e,{plugins:[lgZoom,fullscreen],licenseKey:"0000-0000-000-0000",speed:500,controls:!0,thumbnail:!1,download:!1,mode:"lg-fade",closeOnTap:!0,hideScrollbar:!0,mobileSettings:{showCloseIcon:!0},cssEasing:"cubic-bezier(0.25, 0, 0.25, 1)"})})},addEventListener("scroll",e=>{window.scrollY>document.querySelector("#banner").offsetHeight?document.querySelector("#top").classList.remove("hidden"):document.querySelector("#top").classList.add("hidden")}),document.querySelector("#top").addEventListener("click",function(){window.scrollTo({top:0,behavior:"smooth"})}),document.querySelectorAll("nav a").forEach(e=>{e.addEventListener("click",e=>{e.preventDefault(),scrollToSection(e.currentTarget.getAttribute("href"))})});